name: app workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
jobs:
  secrets-scanning:
    runs-on: ubuntu-latest
    name: secrets scanning
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: scan the repo
        uses: gitleaks/gitleaks-action@v2

  unit-testing:

    needs: secrets-scanning
    runs-on: ubuntu-latest
    name: unit-testing
    steps:
      - name: checkout repo
        uses: "actions/checkout@v4"

      - name: install nodejs
        uses: "actions/setup-node@v4"

      - name : cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: install dependencies
        run: |
          ls -a
          cd Backend
          ls -a
          npm install
            
        

      - name: test the app
        run: | 
              cd Backend
              npm test
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}

      - name: upload test results
        uses: "actions/upload-artifact@v4"
        with:
          name: test-result
          path: ./test-results.xml
# docker-build:
#    name: docker-build
#
#    runs-on: ubuntu-latest
#    needs:
#      - unit-testing
#    steps:
#      - name: repo checkout
#        uses: actions/checkout@v4
#
#      - name: login to docker
#        uses: docker/login-action@v3
#        with:
#          registry:
#          username: ${{vars.DOCKER_USERNAME}}
#          password: ${{secrets.DOCKER_PASSWORD}}
#      - name: build and push to dockerhub
#        uses: docker/build-push-action@v6
#        with:
#          push: true
#          tags: ${{vars.DOCKER_USERNAME}}/cicd-app:latest

#  dev-deploy:
#    name: deploy to k8s cluster
