name: app workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
jobs:
  secrets-scanning:
    runs-on: ubuntu-latest
    name: secrets scanning
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: scan the repo
        uses: gitleaks/gitleaks-action@v2

  unit-testing:

    needs: secrets-scanning
    runs-on: ubuntu-latest
    name: unit-testing
    steps:
      - name: checkout repo
        uses: "actions/checkout@v4"

      - name: install nodejs
        uses: "actions/setup-node@v4"

      - name : cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: install dependencies
        run: |
          npm install
            
        

      - name: test the app
        run: | 
              npm test
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}
          GITHUB_CLIENT_ID: ${{ secrets.CLIENT_ID_GITHUB }}
          GITHUB_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_GITHUB }}
          GITHUB_CALLBACK_URL: ${{ secrets.CALLBACK_URL_GITHUB }}
          SECRET: ${{ secrets.SECRET }}

      - name: Create test results file if missing
        run: touch ./test-results.xml

      - name: upload test results
        uses: "actions/upload-artifact@v4"
        with:
          name: test-result
          path: ./test-results.xml
  docker-build:
    name: docker-build

    runs-on: ubuntu-latest
    needs:
      - unit-testing
    steps:
      - name: repo checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to AWS ECR
        run: |
              aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .

      - name: Tag Docker image
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.ECR_REPOSITORY }}:latest

      - name: push to ecr
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:latest
          
          
          
#      - name: Deploy to EC2
#        uses: appleboy/ssh-action@v0.1.6
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USER }}
#          key: ${{ secrets.EC2_SSH_KEY }}
#          script: |
#            # Login to ECR
#            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
#            docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}
#
#            # Pull latest image
#            docker pull ${{ secrets.ECR_REPOSITORY }}:latest
#
#            # Stop old container (ignore error if not exists)
#            docker stop codiapp1 || true
#            docker rm codiapp1 || true
#
#            # Run new container
#            sudo docker run -d --name codiapp1 \
#            -p 3002:3002 \
#            -e SECRET='${{secrets.SECRET}}' \
#            -e GOOGLE_CLIENT_ID='${{secrets.GOOGLE_CLIENT_ID}}' \
#            -e GOOGLE_CLIENT_SECRET='${{secrets.GOOGLE_CLIENT_SECRET}}' \
#            -e GOOGLE_CALLBACK_URL='${{secrets.GOOGLE_CALLBACK_URL}}' \
#            -e DATABASE_URL='${{secrets.DATABASE_URL}}' \
#            -e GITHUB_CLIENT_ID='${{secrets.CLIENT_ID_GITHUB}}' \
#            -e GITHUB_CLIENT_SECRET='${{secrets.CLIENT_SECRET_GITHUB}}' \
#            -e GITHUB_CALLBACK_URL='${{secrets.CALLBACK_URL_GITHUB}}' \
#            --network my-network \
#            ${{ secrets.ECR_REPOSITORY }}:latest
#
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name cicd-cluster
      - name: Deploy to EKS
        run: |
          kubectl set image deployment/code-together app=${{ secrets.ECR_REPOSITORY }}:latest
            
            
            
           

      

#  vulnerability-scanning:
#    needs: [secrets-scanning,unit-testing, docker-build]
#    name: Run Trivy vulnerability scanner
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Run Trivy vulnerability scanner
#        uses: aquasecurity/trivy-action@0.28.0
#        with:
#            image-ref: '${{vars.DOCKER_USERNAME}}/codetogether:latest'
#            format: 'sarif'
#            output: 'trivy-results.sarif'
#      - name: Upload Trivy scan results to GitHub Security tab
#        uses: github/codeql-action/upload-sarif@v3
#        if: always()
#        with:
#            sarif_file: 'trivy-results.sarif'

